language: python
python:
    - "3.6"
before_install:
    # stuff for the python
    - pip install jinja2
    - pip install arpeggio
    - pip install pytest
    - pip install textx
install:
    - python setup.py install
script:
    - py.test tests

