language: python
python:
    - "3.6"
before_install:
    # Installing textx etc. as a dependency
    - cd ..
    # stuff for the python
    - pip install jinja2
    - pip install arpeggio
    - pip install pytest
    - pip install textx
    - cd ../examc
install:
    - python setup.py install
script:
    - py.test tests

